import { getContext } from '../../../extensions.js';
import { user_avatar } from '../../../../script.js';
import { THEMES, cleanProfile, styleFor, collectPersonas, parseLrc, lyricAt, parsePackage } from './core.mjs';
const KEY='persona_stage';
function boot(){if(document.getElementById('persona-stage-host'))return;const context=getContext();if(!context.extensionSettings)return console.error('[映我] 酒馆扩展接口不可用');let settings=context.extensionSettings[KEY];if(!settings||typeof settings!=='object')settings=context.extensionSettings[KEY]={};settings.profiles??={};settings.uid??=crypto.randomUUID();const save=()=>getContext().saveSettingsDebounced();save();
const host=document.createElement('div');host.id='persona-stage-host';document.body.append(host);const root=host.attachShadow({mode:'open'});const sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href=new URL('./style.css',import.meta.url).href;root.append(sheet);const wrap=document.createElement('div');wrap.innerHTML=`
<button class="launch" title="打开映我人设展示台" aria-label="打开映我人设展示台">✧</button>
<section class="window hidden" aria-label="映我人设展示台"><header><button class="grip" aria-label="拖动展示台">⠿</button><strong>映我 <small>PERSONA STAGE</small></strong><div class="tools"><button data-action="library" title="人设库">人设</button><button data-action="edit" title="布景编辑">布景</button><button data-action="expand" title="展开或缩小">⛶</button><button data-action="hide" title="收起">－</button></div></header>
<div class="stage"><div class="backdrop"></div><canvas></canvas><div class="halo"></div><div class="actors"><figure class="actor main"><img alt="当前人设"><figcaption></figcaption></figure><figure class="actor partner hidden"><img alt="同台人设"><figcaption></figcaption></figure></div><div class="empty hidden">先在酒馆创建或选择一个 user 人设吧。</div><div class="caption"><h2></h2><p class="quote"></p><p class="lyric"></p></div><div class="stage-top"><label><input class="follow" type="checkbox">跟随当前 user</label><button data-action="info" title="人设简介">简介</button></div></div>
<footer><button data-action="play">♫ 播放主题曲</button><span class="playtime"></span><button data-action="cheer">✧ 应援</button><button data-action="motion" title="暂停或恢复动态">动态 开</button></footer><div class="notice" role="status"></div>
<aside class="panel hidden"><div class="panel-head"><h3></h3><button data-action="closePanel" aria-label="关闭面板">✕</button></div><div class="panel-body"></div></aside></section>`;root.append(wrap);const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)],win=$('.window'),stage=$('.stage'),panel=$('.panel'),body=$('.panel-body');
let current='',partner='',personas=[],revision=0,urls=[],db=null,dbPromise,lines=[],motion=!matchMedia('(prefers-reduced-motion: reduce)').matches,opened=false,raf=0,energy=0,ac,analyser,bins,pulses=[],lastFrame=0;const audio=new Audio();audio.preload='metadata';audio.onended=()=>{$('[data-action=play]').textContent='♫ 重新播放';$('.playtime').textContent='演出结束'};audio.ontimeupdate=()=>{$('.lyric').textContent=lyricAt(lines,audio.currentTime);$('.playtime').textContent=`${Math.floor(audio.currentTime/60)}:${String(Math.floor(audio.currentTime%60)).padStart(2,'0')}`};audio.onerror=()=>notify('音乐没能加载，请重新选择素材。');
const profile=id=>cleanProfile(Object.hasOwn(settings.profiles,id)?settings.profiles[id]:{});function put(id,p){if(!id)return;Object.defineProperty(settings.profiles,id,{value:cleanProfile(p),writable:true,enumerable:true,configurable:true});save()}
function notify(text){$('.notice').textContent=text;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('.notice').textContent='',5000)}
function active(){return user_avatar||''}function dataFor(id){return personas.find(x=>x.id===id)||{id,name:'未命名人设',description:''}}function displayName(id){return profile(id).name||dataFor(id).name||'未命名人设'}
function loadPersonas(){const c=getContext();personas=collectPersonas(c.powerUserSettings,active(),c.name1);if(settings.follow!==false&&active())current=active();if(!personas.some(p=>p.id===current))current=active()||personas[0]?.id||'';if(!personas.some(p=>p.id===partner)||partner===current)partner='';$('.follow').checked=settings.follow!==false;render()}
function openDB(){if(dbPromise)return dbPromise;dbPromise=new Promise(resolve=>{try{const req=indexedDB.open('persona-stage-'+settings.uid,1);req.onupgradeneeded=()=>req.result.createObjectStore('assets');req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>resolve(null)}catch{resolve(null)}});return dbPromise}
async function readAsset(id){if(!id)return null;const d=await openDB();if(!d)return null;return new Promise(resolve=>{const q=d.transaction('assets').objectStore('assets').get(id);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>resolve(null)})}
async function storeAsset(blob){const d=await openDB();if(!d)throw Error('本机存储不可用，无法保存素材');const id=crypto.randomUUID();await new Promise((resolve,reject)=>{const tx=d.transaction('assets','readwrite');tx.objectStore('assets').put(blob,id);tx.oncomplete=resolve;tx.onerror=()=>reject(Error('保存失败，可能是浏览器空间不足'))});return id}
async function deleteAsset(id){if(!id)return;const d=await openDB();if(!d)return;d.transaction('assets','readwrite').objectStore('assets').delete(id)}
function stopAudio(){audio.pause();audio.removeAttribute('src');audio.load();$('.playtime').textContent='';$('.lyric').textContent='';$('[data-action=play]').textContent='♫ 播放主题曲'}
async function render(){const token=++revision;stopAudio();urls.forEach(URL.revokeObjectURL);urls=[];const p=profile(current),theme=styleFor(p);for(const key of ['accent','secondary','base'])win.style.setProperty('--'+key,theme[key]);win.style.setProperty('--radius',theme.radius+'px');win.style.setProperty('--type',theme.font==='serif'?'Georgia,"Songti SC",serif':'system-ui,"Microsoft YaHei",sans-serif');win.classList.toggle('light',p.theme==='candy');win.dataset.effect=theme.effect;$('.empty').classList.toggle('hidden',!!current);$('.main').classList.toggle('hidden',!current);$('.partner').classList.toggle('hidden',!partner);$('.actors').classList.toggle('duo',!!partner);$('.caption h2').textContent=current?displayName(current)+(partner?' × '+displayName(partner):''):'';$('.quote').textContent=p.quote;lines=parseLrc(p.lyrics);
const entries=[[current,'.main'],[partner,'.partner']];for(const [id,selector] of entries){const figure=$(selector);if(!id)continue;const cfg=profile(id);figure.style.setProperty('--scale',cfg.scale);figure.style.setProperty('--y',cfg.offsetY+'%');figure.style.opacity=cfg.opacity;const img=figure.querySelector('img');img.style.objectFit=cfg.fit;img.alt=displayName(id);figure.querySelector('figcaption').textContent=displayName(id);const avatar=getContext().getThumbnailUrl?.('persona',id)||'/User%20Avatars/'+encodeURIComponent(id);img.src=avatar;img.onerror=()=>{img.onerror=null;img.removeAttribute('src');notify('头像无法读取，可以在布景里添加立绘。')};const blob=await readAsset(cfg.image);if(token!==revision)return;if(blob){const url=URL.createObjectURL(blob);urls.push(url);img.src=url}}
$('.backdrop').style.backgroundImage='none';const bg=await readAsset(p.background);if(token!==revision)return;if(bg){const url=URL.createObjectURL(bg);urls.push(url);$('.backdrop').style.backgroundImage=`url("${url}")`}const music=await readAsset(p.music);if(token!==revision)return;audio.volume=p.volume;if(music){const url=URL.createObjectURL(music);urls.push(url);audio.src=url}$('[data-action=play]').disabled=!music;$('[data-action=play]').title=music?'播放当前人设的主题曲':'在布景里添加主题曲';if((p.image&&!await readAsset(p.image))||(p.music&&!music))notify('当前设备缺少素材，可导入完整布景包恢复。');}
function show(){opened=true;win.classList.remove('hidden');$('.launch').classList.add('hidden');clamp();startAnimation()}function hide(){opened=false;win.classList.add('hidden');$('.launch').classList.remove('hidden');audio.pause();$('[data-action=play]').textContent='♫ 播放主题曲';cancelAnimationFrame(raf)}$('.launch').onclick=show;
function showPanel(title){$('.panel-head h3').textContent=title;body.replaceChildren();panel.classList.remove('hidden')}
function el(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e}function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b}
function library(){showPanel('人设库');const search=document.createElement('input');search.placeholder='搜索名字、分组、标签';search.type='search';search.setAttribute('aria-label','搜索人设');body.append(search);const list=el('div',null,'cards');body.append(list);const refresh=()=>{list.replaceChildren();const q=search.value.toLocaleLowerCase();for(const persona of personas){const p=profile(persona.id);if(![displayName(persona.id),p.owner,p.tags].join(' ').toLocaleLowerCase().includes(q))continue;const card=el('div',null,'card');const image=el('img');image.alt='';image.src=getContext().getThumbnailUrl?.('persona',persona.id)||'/User%20Avatars/'+encodeURIComponent(persona.id);image.onerror=()=>image.remove();const details=el('div');details.append(el('strong',displayName(persona.id)),el('small',[p.owner,p.tags,persona.id===active()?'当前 user':''].filter(Boolean).join(' · ')));const row=el('div',null,'row');row.append(button(persona.id===current?'展示中':'展示',()=>{current=persona.id;settings.follow=false;save();$('.follow').checked=false;if(partner===current)partner='';render();refresh()}));if(persona.id!==current)row.append(button(partner===persona.id?'取消同台':'一起展示',()=>{partner=partner===persona.id?'':persona.id;render();refresh()}));details.append(row);card.append(image,details);list.append(card)}if(!list.children.length)list.append(el('p','没有匹配的人设。'))};search.oninput=refresh;refresh();body.append(el('p','这里仅切换展示，不会改变聊天中选用的 user。','hint'))}
function info(){showPanel('人设简介');for(const id of [current,partner].filter(Boolean)){body.append(el('h4',displayName(id)),el('p',profile(id).description||dataFor(id).description||'这个人设还没有描述。','description'))}}
function control(label,type,value,onchange,options={}){const row=el('label',null,'field');row.append(el('span',label));let input;if(type==='select'){input=el('select');for(const [v,t] of options.values){const o=el('option',t);o.value=v;input.append(o)}}else if(type==='textarea')input=el('textarea');else{input=el('input');input.type=type}for(const [k,v]of Object.entries(options))if(k!=='values')input[k]=v;input.value=value;input.onchange=()=>onchange(input.value);row.append(input);body.append(row);return input}
function edit(){if(!current){notify('先在酒馆选一个 user 人设。');return}showPanel('布景 · '+displayName(current));const id=current;const change=(key,value)=>{put(id,{...profile(id),[key]:value});render()};control('主题预设','select',profile(id).theme,v=>{put(id,{...profile(id),theme:v,accent:'',secondary:'',base:'',font:'',effect:'',radius:null});render();edit()},{values:Object.entries(THEMES).map(([k,v])=>[k,v.name])});const p=profile(id);control('展示名字（空白跟随酒馆）','text',p.name,v=>change('name',v));control('分组 / 所属','text',p.owner,v=>change('owner',v));control('标签','text',p.tags,v=>change('tags',v));control('代表台词','textarea',p.quote,v=>change('quote',v));control('展示简介（空白跟随酒馆）','textarea',p.description,v=>change('description',v));const style=styleFor(p);for(const [k,label]of [['accent','主色'],['secondary','辅助色'],['base','底色']])control(label,'color',style[k],v=>change(k,v));control('字体','select',style.font,v=>change('font',v),{values:[['sans','简洁无衬线'],['serif','衬线 / 宋体']]});control('边框圆角','range',style.radius,v=>change('radius',Number(v)),{min:0,max:36,step:1});control('舞台特效','select',style.effect,v=>change('effect',v),{values:[['laser','霓虹光束'],['stars','漂浮星光'],['snow','落雪'],['none','关闭']]});control('立绘缩放','range',p.scale,v=>change('scale',Number(v)),{min:.5,max:2,step:.05});control('立绘上下位置','range',p.offsetY,v=>change('offsetY',Number(v)),{min:-40,max:40,step:1});control('投影不透明度','range',p.opacity,v=>change('opacity',Number(v)),{min:.15,max:1,step:.05});control('图片显示','select',p.fit,v=>change('fit',v),{values:[['contain','完整显示'],['cover','填满投影位']]});
body.append(el('h4','本机素材'),el('p','素材存在当前浏览器；换设备或分享给朋友，请导出含素材的布景包。','hint'));
for(const [key,title,accept]of [['image','人物立绘','image/png,image/jpeg,image/webp'],['background','舞台背景','image/png,image/jpeg,image/webp'],['music','主题曲','audio/*']]){const field=el('label',title,'file');const input=el('input');input.type='file';input.accept=accept;input.onchange=async()=>{const file=input.files[0];if(!file)return;const max=key==='music'?20:8;if(file.size>max*1024*1024){notify(`请选 ${max} MB 以内的素材。`);return}if(key!=='music'&&!['image/png','image/jpeg','image/webp'].includes(file.type)){notify('图片请用 PNG、JPG 或 WebP。');return}if(key==='music'&&!file.type.startsWith('audio/')){notify('请选择音频文件。');return}try{if(key!=='music'){const im=await createImageBitmap(file);im.close()}const old=profile(id)[key],asset=await storeAsset(file);change(key,asset);await deleteAsset(old);notify('素材已保存。')}catch(e){notify(e.message)}};field.append(input);body.append(field,button('清除'+title,async()=>{const old=profile(id)[key];change(key,'');await deleteAsset(old);notify('已清除'+title)}))}
control('歌词 LRC（可粘贴时间轴）','textarea',p.lyrics,v=>change('lyrics',v));const lrc=el('label','导入 LRC 文件','file'),lrcInput=el('input');lrcInput.type='file';lrcInput.accept='.lrc,.txt';lrcInput.onchange=async()=>{const f=lrcInput.files[0];if(f&&f.size<500000){change('lyrics',await f.text());edit();notify('歌词已导入。')}};lrc.append(lrcInput);body.append(lrc);control('主题曲音量','range',p.volume,v=>change('volume',Number(v)),{min:0,max:1,step:.05});
const copyOptions=[['','选择人设…'],...personas.filter(x=>x.id!==id).map(x=>[x.id,displayName(x.id)])];control('复制另一人设的布景','select','',async other=>{if(!other)return;try{const source=profile(other);const next={...source,name:p.name,description:p.description,quote:p.quote,owner:p.owner,tags:p.tags};for(const k of ['image','background','music']){const blob=await readAsset(source[k]);next[k]=blob?await storeAsset(blob):''}put(id,next);render();edit();notify('已复制布景，原人设不受影响。')}catch(e){notify(e.message)}},{values:copyOptions});body.append(button('导出完整布景包',()=>exportPackage(id)),button('导入布景包到此人设',()=>importPackage(id)));}
async function asData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}
async function exportPackage(id){try{const p=profile(id),assets={};for(const k of ['image','background','music']){const b=await readAsset(p[k]);if(b)assets[k]=await asData(b)}const payload={format:'persona-stage',version:1,profile:{...p,name:p.name||dataFor(id).name,description:p.description||dataFor(id).description,image:'',background:'',music:''},assets};parsePackage(payload);const blob=new Blob([JSON.stringify(payload)],{type:'application/json'});const a=el('a');a.href=URL.createObjectURL(blob);a.download='映我-'+displayName(id).replace(/[\\/:*?"<>|]/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);notify('布景包已导出，包含展示简介和所选素材。')}catch(e){notify(e.message||'导出失败')}}
function importPackage(id){const input=el('input');input.type='file';input.accept='.json';input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>42*1024*1024){notify('文件太大，请控制在 42 MB 以内。');return}const created=[];try{const parsed=parsePackage(JSON.parse(await f.text()));for(const k of ['image','background','music']){parsed.profile[k]='';if(parsed.assets[k]){const b=await (await fetch(parsed.assets[k])).blob();parsed.profile[k]=await storeAsset(b);created.push(parsed.profile[k])}}const old=profile(id);put(id,parsed.profile);for(const k of ['image','background','music'])await deleteAsset(old[k]);render();edit();notify('已导入，仅更新展示台布景。')}catch(e){for(const asset of created)await deleteAsset(asset);notify(e.message||'导入失败')}};input.click()}
async function toggleMusic(){if(!audio.src)return;try{if(!audio.paused){audio.pause();$('[data-action=play]').textContent='♫ 播放主题曲';return}if(!ac){ac=new(window.AudioContext||window.webkitAudioContext)();analyser=ac.createAnalyser();analyser.fftSize=128;const source=ac.createMediaElementSource(audio);source.connect(analyser);analyser.connect(ac.destination);bins=new Uint8Array(analyser.frequencyBinCount)}await ac.resume();await audio.play();$('[data-action=play]').textContent='Ⅱ 暂停'}catch{notify('无法播放这段音频，请试试 MP3。')}}
$('.follow').onchange=e=>{settings.follow=e.target.checked;save();loadPersonas()};root.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;({library,edit,info,play:toggleMusic,closePanel:()=>panel.classList.add('hidden'),hide,expand:()=>{win.classList.toggle('expanded');clamp()},cheer:()=>{pulses.push(performance.now());if(pulses.length>8)pulses.shift();notify('✧ 星光送达 '+displayName(current))},motion:()=>{motion=!motion;$('[data-action=motion]').textContent='动态 '+(motion?'开':'关');win.classList.toggle('still',!motion)}}[action])?.()});
function clamp(){if(win.classList.contains('expanded'))return;const pos=settings.position||{x:innerWidth-340,y:100};const x=Math.max(0,Math.min(pos.x,innerWidth-Math.min(330,innerWidth))),y=Math.max(0,Math.min(pos.y,innerHeight-120));win.style.left=x+'px';win.style.top=y+'px'}let drag=null;$('.grip').onpointerdown=e=>{if(win.classList.contains('expanded'))return;drag={x:e.clientX,y:e.clientY,left:win.offsetLeft,top:win.offsetTop};e.currentTarget.setPointerCapture(e.pointerId)};$('.grip').onpointermove=e=>{if(!drag)return;settings.position={x:drag.left+e.clientX-drag.x,y:drag.top+e.clientY-drag.y};clamp()};$('.grip').onpointerup=$('.grip').onpointercancel=()=>{if(drag){drag=null;save()}};addEventListener('resize',clamp);root.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!panel.classList.contains('hidden'))panel.classList.add('hidden');else hide()}});
const canvas=$('canvas'),ctx=canvas.getContext('2d');function startAnimation(){cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}function draw(ms){raf=requestAnimationFrame(draw);if(document.hidden||!opened||ms-lastFrame<33)return;lastFrame=ms;const w=stage.clientWidth,h=stage.clientHeight,dpr=Math.min(devicePixelRatio||1,1.5);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const t=motion?ms/1000:0,style=styleFor(profile(current));if(analyser&&!audio.paused&&motion){analyser.getByteFrequencyData(bins);energy=bins.slice(0,20).reduce((a,b)=>a+b,0)/5100}else energy=0;if(style.effect==='none')return;ctx.globalAlpha=.3;ctx.strokeStyle=style.secondary;ctx.lineWidth=1;for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(w/2,h*.82,w*(.2+i*.075),h*(.025+i*.02),0,0,Math.PI*2);ctx.stroke()}if(style.effect==='laser'){for(let i=0;i<8;i++){ctx.strokeStyle=i%2?style.accent:style.secondary;ctx.globalAlpha=.14+energy*.25;ctx.beginPath();ctx.moveTo(w*(i/7),h*.85);ctx.lineTo(w*(.5+Math.sin(t*.3+i)*.7),0);ctx.stroke()}for(let i=0;i<70;i++){ctx.globalAlpha=.4;ctx.fillStyle=i%2?style.accent:style.secondary;ctx.fillRect((i*67%997)/997*w,h*(.91+(i%4)*.015),2,5+energy*4)}}else{for(let i=0;i<45;i++){ctx.globalAlpha=.15+(i%5)*.12;ctx.fillStyle=i%2?style.accent:style.secondary;const x=(i*73%997)/997*w+Math.sin(t*.2+i)*8,y=((i*53%991)/991*h+t*(style.effect==='snow'?12:2))%h;ctx.beginPath();ctx.arc(x,y,style.effect==='snow'?1.6:1,0,Math.PI*2);ctx.fill()}}for(const stamp of pulses){const a=(ms-stamp)/1000;if(a>2)continue;ctx.globalAlpha=(1-a/2)*.7;ctx.strokeStyle=style.accent;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(w/2,h*.8,a*w*.5,a*h*.15,0,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1}
function refreshed(){loadPersonas();if(!panel.classList.contains('hidden'))panel.classList.add('hidden')}for(const key of ['PERSONA_CHANGED','PERSONA_UPDATED','PERSONA_RENAMED','PERSONA_CREATED','PERSONA_DELETED','CHAT_CHANGED']){const ev=context.eventTypes?.[key];if(ev)context.eventSource.on(ev,refreshed)}if(context.eventTypes?.SETTINGS_UPDATED)context.eventSource.on(context.eventTypes.SETTINGS_UPDATED,()=>{const p=collectPersonas(getContext().powerUserSettings,active(),getContext().name1);if(JSON.stringify(p)!==JSON.stringify(personas))refreshed()});
loadPersonas();win.classList.toggle('still',!motion);$('[data-action=motion]').textContent='动态 '+(motion?'开':'关');
const mount=document.querySelector('#extensions_settings2')||document.querySelector('#extensions_settings');
if(mount){
    const entry=el('div');
    entry.id='persona-stage-settings';
    const b=button(null,show);
    b.id='persona-stage-open';
    b.className='menu_button menu_button_icon';
    b.title='打开映我 · 人设展示台';
    const icon=el('span','✧','persona-stage-entry-icon');
    icon.setAttribute('aria-hidden','true');
    b.append(icon,el('span','打开映我 · 人设展示台','persona-stage-entry-label'));
    entry.append(b);
    mount.append(entry);
}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
